{% set version = "0.1.5" %}

package:
  name: django-fixture-magic
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-fixture-magic/django-fixture-magic-{{ version }}.tar.gz
  sha256: d82a4d4f6ade078e942927b5157f0536d0cd0232adfeb943dced0858128dd734

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - fixture_magic
    - fixture_magic.management
    - fixture_magic.management.commands

about:
  home: http://github.com/davedash/django-fixture-magic
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A few extra management tools to handle fixtures.

extra:
  recipe-maintainers:
    - ocefpaf
