travis:
  secure:
    BINSTAR_TOKEN: d8d4xS79JjB0TL9D+vbWejBiYmN8xDE4U36m+2/xokmT8Wuf9DvLI1sZyeyZt5xzeMoujv7BK7UYjapxNTnTfzLiHekSHOZOijw8TRnXbysxL6oZ/JDVnM49kdgnZFxAx5sX3anAbGztl18okVtlStU7bpbJ4AgJFEQSTlmneDdKqK3HrdNzcixK5/5+skxVPQsvp2ufH7mURIpxadRUSKITJYOxzbOEcuE94JnYAxj8xE/873UX+/cbujJmvCECv6CohG4M4gYIl29DSdhe75VUZCasuthTjfaud4kXG/zJW0TpdGrPHyaDBTxFqv638/cfaB6+N+zKNrfV6TiXyEBJTJvmVENYhGTNKI610RrcGfXZ/vQChhsZl3sEMWqaCu5LQswBiSWDrCd6sufhWZobObQYjBWtiqMuKbMCMwFDV34a9YeJYb6HlRRSTvID6bTeG79GeMT7+66SBaa5M2Yzpuop7Gah71osxMNTqAKdKY6oB6GCg1f1HrmlrMn/6Ox5L9NBTN5MhCj+TFgJkgD21iUmkEIWz0v51o0EHbPpV9qxt44kddq6R4fjTMnP808DUFnQHMPe1jYNHG++jqLVuF6We/gRsVj1HjLrO3dJhZB679iA4f4DrCf0lXC8YXc4YeBfnAW82XRnMtyJbF+n4epvFrPqplEm9hv3VP0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
